---
version: 5
defaults:  
  datadir: hieradata  
  data_hash: yaml_data  
hierarchy:
  - name: "Nodes"
    path: "nodes/%{::trusted.certname}.yaml"
  - name: "Common data"
    path: "common.yaml"

# datadir defaults are:
# - /etc/puppetlabs/code/environments/%{environment}/hieradata on *nix
# - %CommonAppData%\PuppetLabs\code\environments\%{environment}\hieradata on Windows
# When specifying a datadir, make sure the directory exists.
